# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Vero News
tagline:          'Vero news'
description:      'Stay up to date with the latest Vero developments as they happen!'
url:              http://progress.getvero.tv
paginate:         5
baseurl:          /
