# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Vero Blog
tagline:          'Your Vero'
description:      'Stay up to date with the latest Vero developments'
url:              http://progress.getvero.tv
paginate:         5
baseurl:          /
